baseurl = "/"
languageCode = "en-us"
title = "Marco's blog"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Contact Me"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/GuozySCU"
[[menu.main]]
    name = "JianShu"
    url = "https://www.jianshu.com/u/f6dd913dbbf4"
[[menu.main]]
    name = "Projects"
    url = "/2019-05-13-projects.md/"
[params]
    description = "All work and no play makes you a dull boy."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "gzzy.jpg"
    width = 60
    height = 60
    alt = "Logo"


